---
name: Deploy Python functions to AWS Lambda

on:
  push:
    branches:
      - 'main'
    paths:
      - 'lambda/get_all_inventory_items/lambda_function.py'
      - 'lambda/get_inventory_item/lambda_function.py'
      - 'lambda/get_location_inventory_items/lambda_function.py'
      - 'lambda/add_inventory_item/lambda_function.py'
      - 'lambda/delete_inventory_item/lambda_function.py'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          
      - name: Zip the get_all_inventory_items Lambda function
        run: zip function.zip lambda_function.py
        working-directory: ./lambda/get_all_inventory_items
      - name: Update get_all_inventory_items code
        run: aws lambda update-function-code --function-name get_all_inventory_items --zip-file fileb://function.zip --publish
        working-directory: ./lambda/get_all_inventory_items
      - name: Cleanup get_all_inventory_items zip
        run: rm function.zip
        working-directory: ./lambda/get_all_inventory_items

      - name: Zip the get_inventory_item Lambda function
        run: zip function.zip lambda_function.py
        working-directory: ./lambda/get_inventory_item
      - name: Update get_inventory_item code
        run: aws lambda update-function-code --function-name get_inventory_item --zip-file fileb://function.zip --publish
        working-directory: ./lambda/get_inventory_item
      - name: Cleanup get_inventory_item zip
        run: rm function.zip
        working-directory: ./lambda/get_inventory_item

      - name: Zip the get_location_inventory_items Lambda function
        run: zip function.zip lambda_function.py
        working-directory: ./lambda/get_location_inventory_items
      - name: Update get_location_inventory_items code
        run: aws lambda update-function-code --function-name get_location_inventory_items --zip-file fileb://function.zip --publish
        working-directory: ./lambda/get_location_inventory_items
      - name: Cleanup get_location_inventory_items zip
        run: rm function.zip
        working-directory: ./lambda/get_location_inventory_items

      - name: Zip the add_inventory_item Lambda function
        run: zip function.zip lambda_function.py
        working-directory: ./lambda/add_inventory_item
      - name: Update add_inventory_item code
        run: aws lambda update-function-code --function-name add_inventory_item --zip-file fileb://function.zip --publish
        working-directory: ./lambda/add_inventory_item
      - name: Cleanup add_inventory_item zip
        run: rm function.zip
        working-directory: ./lambda/add_inventory_item

      - name: Zip the delete_inventory_item Lambda function
        run: zip function.zip lambda_function.py
        working-directory: ./lambda/delete_inventory_item
      - name: Update delete_inventory_item code
        run: aws lambda update-function-code --function-name delete_inventory_item --zip-file fileb://function.zip --publish
        working-directory: ./lambda/delete_inventory_item
      - name: Cleanup delete_inventory_item zip
        run: rm function.zip
        working-directory: ./lambda/delete_inventory_item
